### ISSUE TITLE
PRONLEM Tiktok-Account-Massreport-main

### ISSUE THREAD

**Issue by lmjhn** [H4cK3dR4Du/Tiktok-Account-Massreport#10]
Hello.. please can you help me

Traceback (most recent call last):
  File "main.py", line 87, in <module>
    if data["proxy_scraper"] == "y" or data["proxy_scraper"] == "yes":
TypeError: string indices must be integers

Thank you..

**Comment by lmjhn** [comment]
Traceback (most recent call last):
  File "main.py", line 86, in <module>
    data = json.load(f)
  File "C:\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 2 column 1337 (char 1338)

**Comment by AxthonyV** [comment]
As I understand you have an invalid character in the .json file, please check that there are no strange characters, you can also send me the .json so I can check it

the file should look like this with the url already implemented:

![config](https://github.com/H4cK3dR4Du/Tiktok-Account-Massreport/assets/141282212/36cefa94-53a3-40c6-b83e-2d52261f986c)
